kind: ServiceAccount
apiVersion: v1
metadata:
  name: kemt-svc-acc
  namespace: kemt
automountServiceAccountToken: true
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kemtk
  name: kemt-clusterrole
rules:
  - apiGroups: ["", "extensions", "kubernetes-misc.xyz"]
    resources: ["events", "kemts"]
    verbs: ["get", "list", "watch" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kemt-clusterrole-binding
  namespace: kemt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kemt-clusterrole
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: kemt-svc-acc
    namespace: kemt

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kemt
  name: kemt-clusterrole-read-all
rules:
  - apiGroups: ["", "extensions"]
    resources: ["deployments", "pods", "services", "logs"]
    verbs: ["get", "list", "watch" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kemt-clusterrole-binding-read-all
  namespace: kemt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kemt-clusterrole-read-all
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: kemt-svc-acc
    namespace: kemt