
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kemt-svc-acc
  namespace: cluster-infra # The svc acc should be in the same ns as the pod mounting it
automountServiceAccountToken: true
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kemt-clusterrole
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["events"]
    verbs: ["get", "list", "watch" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kemt-clusterrole-binding
  namespace: cluster-infra # The service account mounted by the pod should live it the same ns as the pod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kemt-clusterrole
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: kemt-svc-acc
    namespace: cluster-infra #Try 2

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kemt-clusterrole-read-all
rules:
  - apiGroups: ["", "extensions"]
    resources: ["deployments", "pods", "pods/log", "services", "logs", "namespaces"]
    verbs: ["get", "list", "watch" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kemt-clusterrole-binding-read-all
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kemt-clusterrole-read-all
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: kemt-svc-acc
    namespace: cluster-infra