apiVersion: v1
kind: Service
metadata:
  name: kemt
spec:
  ports:
    - name: kemt-port
      nodePort: 30000
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: kemt
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kemt
  namespace: kemt
spec:
  selector:
    matchLabels:
      app: kemt
  template:
    metadata:
      labels:
        app: kemt
    spec:
      serviceAccountName: kemt-svc-acc
      containers:
        - env:
            - name: authInCluster
              value: "true"
            - name: listen
              value: ":8080"
          image: kubernetesmisc/kemt:latest
          imagePullPolicy: Always
          name: kemt
          resources:
            limits:
              cpu: 500m
              memory: 64Mi
            requests:
              memory: 64Mi
          ports:
            - name: kemt-port
              containerPort: 8080
              protocol: TCP
